// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0001_uploaded_files.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createMetadata = `-- name: CreateMetadata :execresult
INSERT INTO ` + "`" + `uploaded_files` + "`" + ` (
    id,
    original_name,
    s3_key,
    mime_type,
    file_size,
    created_at,
    expired_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMetadataParams struct {
	ID           string
	OriginalName string
	S3Key        string
	MimeType     string
	FileSize     int64
	CreatedAt    time.Time
	ExpiredAt    time.Time
}

func (q *Queries) CreateMetadata(ctx context.Context, arg CreateMetadataParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMetadata,
		arg.ID,
		arg.OriginalName,
		arg.S3Key,
		arg.MimeType,
		arg.FileSize,
		arg.CreatedAt,
		arg.ExpiredAt,
	)
}
