// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0001_share_files.sql

package database

import (
	"context"
)

const getMetadataByID = `-- name: GetMetadataByID :one
SELECT
    id,
    s3_key,
    mime_type
FROM ` + "`" + `uploaded_files` + "`" + `
WHERE is_deleted = 0 AND id = ?
`

type GetMetadataByIDRow struct {
	ID       string
	S3Key    string
	MimeType string
}

func (q *Queries) GetMetadataByID(ctx context.Context, id string) (GetMetadataByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMetadataByID, id)
	var i GetMetadataByIDRow
	err := row.Scan(&i.ID, &i.S3Key, &i.MimeType)
	return i, err
}
