// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type UploadedFile struct {
	ID            string
	OriginalName  string
	S3Key         string
	MimeType      string
	FileSize      int64
	CreatedAt     time.Time
	ExpiredAt     time.Time
	DownloadCount int32
	IsDeleted     int32
}
