// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type UploadedFile struct {
	ID            string
	OriginalName  string
	S3Key         string
	MimeType      string
	FileSize      int64
	CreatedAt     sql.NullTime
	ExpiredAt     sql.NullTime
	DownloadCount int32
	IsDeleted     int32
}
