// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/anle/codebase/internal/upload/application/usecase"
	"github.com/anle/codebase/internal/upload/infrastructure/persistence/repository"
	"github.com/anle/codebase/internal/upload/interfaces/http/handler"
)

// Injectors from upload.wire.go:

func InitUploadRouterHandler(dbc *sql.DB) (*handler.UploadHandler, error) {
	iUploadRepository := repository.NewUploadRepository(dbc)
	iUploadService := usecase.NewUploadService(iUploadRepository)
	uploadHandler := handler.NewUploadHandler(iUploadService)
	return uploadHandler, nil
}
